### PR TITLE
Fix issue with use_directory_urls = True configuration

### LINKED ISSUE #24: Link not correctly taken over by plugin
I have an issue with links incorrectly marked as not found. To reproduce the issue I created an empty project with just two files and the following structure
```
docs/page1.md
docs/directory1/page2.md
```

page1.md 
``` 
## Section One
```

page2.md
```
[thelink](../page1.md#section-2)
```

The link in page2 is incorrectly regarded as not existing 
```
Warning: Unable to locate Markdown source file for: ../page1/
ERROR    -  Error building page 'directory1/page2.md':
ERROR    -  ../../page1/#section1: 404
```

It seems to append an extra `../` to the link.

### PR DESCRIPTION
**Pull request by johnthagen**
Closes #24

### CODE REVIEW

**Comment by johnthagen** [comment]
@manuzhang Could you please review?

@koenvervloesem Could you validate that this solves your issue? Note that if you want the cross-page anchor validation to be enabled moving forward, you'll need to set:

```yaml
use_directory_urls: False
```

**Comment by koenvervloesem** [comment]
Sorry, which issue are you referring to?

**Comment by johnthagen** [comment]
@koenvervloesem Sorry I meant to tag someone else. Apologize for the notification.

**Comment by manuzhang** [comment]
@johnthagen Is it possible to add a test with `use_directory_urls = True ` ?

**Comment by johnthagen** [comment]
> @johnthagen Is it possible to add a test with `use_directory_urls = True` ?

Great idea. Done.

**Comment by kkwekkeboom** [comment]
@johnthagen I tested both an incorrect and a correct anchor link with the option `use_directory_urls = False` and this seems to work. Perhaps add a testcase where the anchor link target does not exist?

With `use_directory_urls = True` anchor links are not checked. This is documented in the MR.

**Review by manuzhang — APPROVED** [review]

**Pull request merged**
