### PR TITLE
Consider url scheme to detect and handle external URLs

### LINKED ISSUE #54: mailto: links generate 404 errors
If the document contains mailto: links the plugin returns 404 for each of them.

**To Reproduce**
create a mailto: link (for example `mailto:toto@toto.com`) in a source .md file and build your documentation.

It should simply ignore mailto links.

### PR DESCRIPTION
**Pull request by kolibri91**
This PR improves the plugin by doing two things:

* External urls are detected via scheme
* External urls are handled regarding their scheme

Further, I improved the logging by using the provided functionality of `mkdocs.utils.log`.

Unfortunately, I noticed there are several `flake8` issues in the existing code after my changes.
They are not correctly recognized like I showed in #55.
I fixed them all in this branch, I would prefer if we could merge those changes pragmatic in that PR and avoid a extract and conflict resolution.

Closes #54 
Closes #55

### CODE REVIEW

**Comment by manuzhang** [comment]
LGTM. Please fix styles issues in #55

**Comment by kolibri91** [comment]
- [ ] Merge `main` after #55, it's expected to work without conflicts by using default *ort*-strategy.

**Comment by kolibri91** [comment]
@manuzhang Did you consider to activate branch protection rule "up to date". This would ensure that the PRs contains latest changes.

**Comment by manuzhang** [comment]
It doesn't have to as long as there's no conflict.

**Comment by kolibri91** [comment]
I noticed in my daily work two common issues with branches which are not up to date before you merge.

It can happen that the ci dies not work correctly if main branch contains CI configuration updates. That would be the case here. Fortunately, I noticed the issues during development of this branch.

Secondly, auto-merge can break styling.

**Review by manuzhang — APPROVED** [review]

**Pull request merged**
