### PR TITLE
Refactor plugin to use newer Python 3 features

### PR DESCRIPTION
**Pull request by johnthagen**
- Use f-strings rather than `str.format`
- Sort imports
- Remove redundant parenthesis
- Add type hints to aid in static analysis (PyCharm/VS Code completion, etc)
- Use `@staticmethod` to limit scope on function

### CODE REVIEW

**Comment by manuzhang** [comment]
@johnthagen can we catch these issues during build by adding some flake8 rules ?

**Comment by johnthagen** [comment]
For the type annotations we could use [`mypy`](https://mypy.readthedocs.io/en/stable/) at build time to catch that the type hints are correct.

For import sorting, we could use [`isort`](https://pypi.org/project/isort/).

If you'd like to look at how a project could be set up using these, you can see my [`python-blueprint`](https://github.com/johnthagen/python-blueprint) project.

**Comment by johnthagen** [comment]
@manuzhang I've added `isort` and `mypy` to the CI.

**Review by manuzhang — APPROVED** [review]

**Comment by manuzhang** [comment]
@johnthagen merged. Any more you want to add into next release ?

**Comment by johnthagen** [comment]
Nope, I think this should be good.

#18 would be really important at some point, but I'm not really sure how that would be done. And in any case that would be a follow on release.

**Pull request merged**
