### PR TITLE
Support Local Links without anchor

### PR DESCRIPTION
**Pull request by kolibri91**
I originally started with the problem of a link without an anchor.
Those links are currently just ignored. I changed this by another regex.
But then I ran into trouble with other files (e.g. graphics in combination with `glightbox`-plugin) which have may a link as well.

# Solution
1. Accept links without anchor
2. Check if it targets markdown -> use existing code and search for anchor if there is one
3. Other target -> just look for the source file

## Optimization
1. I optimized the code by using dict, I have no strong opinion about that and I could revert this if required.

### CODE REVIEW

**Comment by manuzhang** [comment]
@kolibri91 thanks for contribution. Could you add an integration test as well?

**Comment by manuzhang** [comment]
Is the image file hand-drawn or from the web? Shall we add an attribution?

**Comment by kolibri91** [comment]
> Is the image file hand-drawn or from the web? Shall we add an attribution?

Handdrawn by me in 2mins. Not worth to have an attribution.

**Comment by manuzhang** [comment]
@kolibri91 Thanks! LGTM, merging...

**Review by manuzhang — APPROVED** [review]

**Pull request merged**
